name: Auto Versioning

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix safe.directory
        run: git config --global --add safe.directory /mnt/c/DR/Nextcloud/BUILD/taunewlety

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor # This will increment 0.1 -> 0.2
          PRERELEASE: false
          INITIAL_VERSION: 0.1.0
